# This file creates a conda environment for the get_crosslinks_coverage module
#   conda env create -f environment.yml
name: nfcore-module-getcrosslinkscoverage
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pigz=2.3.4
  - perl-io-uncompress-gunzip