# You can use this file to create a conda environment for the nf-core icount module:
#   conda env create -f environment.yml
name: nfcore-module-icount
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pigz=2.3.4
  - bedtools=2.28.0
  - star=2.7.3a

