# This file creates a conda environment for the fastqc module
#   conda env create -f environment.yml
name: nfcore-module-fastqc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.8