# Dependencies
markdown: kramdown
highlighter: rouge # changed from `pygments` as github says so

# Permalinks
permalink: pretty

# Setup
title: "Otic reprogramming"
tagline: "Sox8 induced otic reprogramming"
description: "Documentation for github repository"
# url: https://alexthiery.github.io/otic-reprogramming/
url: "http://localhost:4000"
baseurl: ""
paginate: 5
paginate_path: "/blog/page:num/"

author:
  name: "Alex Thiery"
  email: "alexthiery1@gmail.com"
  github: alexthiery/otic-reprogramming
  orcid: http://orcid.org/0000-0002-5814-4977
