# Setup
title: Otic reprogramming
tagline: "Buzzi et al. 2022"
description: 'Documentation for the Buzzi et al. 2022 <a href="https://github.com/alexthiery/otic-reprogramming" target="_blank">Github repository</a>.'

# url: "http://localhost:3000"
# baseurl: ""

url: "https://alexthiery.github.io/otic-reprogramming"
baseurl: "https://alexthiery.github.io/otic-reprogramming"

permalink: pretty
repository: alexthiery/otic-reprogramming

github:
  repo: https://github.com/alexthiery/otic-reprogramming
  author: "https://github.com/alexthiery/"

# About/contact
author:
  name: "Alex Thiery"
  email: "alexthiery1@gmail.com"

lab:
  homepage: https://www.kcl.ac.uk/people/andrea-streit
  publication: https://github.com/alexthiery/otic-reprogramming

  # Dependencies
markdown: CommonMarkGhPages

commonmark:
  options: ["UNSAFE"]

highlighter: rouge

collections:
  downstream:
    output: true
    permalink: /downstream/:path/

  general:
    output: true
    permalink: /general/:path/

  home:
    output: true
    permalink: /home/:path/
