name: docker-build-push

on:
  push:
    branches:
      - master
    paths:
      - modules/r_analysis/Dockerfile

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/otic-reprogramming-r_analysis
          path: modules/r_analysis
          dockerfile: modules/r_analysis/Dockerfile
          tags: latest
