name: docker-build-push-antler-dev

on:
  push:
    branches: [ master ]
    paths: 
      - 'modules/antler-dev/Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/modules-antler-dev
          path: modules/antler-dev
          dockerfile: modules/antler-dev/Dockerfile
          tags: latest