name: docker-build-push-antler

on:
  push:
    branches: [ master ]
    paths: [ './modules/antler/Dockerfile' ]

    jobs:
      build-push-docker:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Build and push master image
            uses: docker/build-push-action@v1.0.1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: alexthiery/modules-antler-dev
              tags: latest