name: docker-pull

on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  docker-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: |
          lastrepo=""
          lastseen=""
          for image in $(cat repos.txt); do
             # Parse repository name, we will remove the previous image if different
             readarray -d : -t repository <<< "$image"
             if [ "${lastseen}" != "" ] && [ "${repository[0]}" != "${lastseen}" ]; then
                 printf "Removing image ${lastseen} to make room."
                 docker rmi "${lastrepo}" || docker rmi "${lastseen}"
             fi
             lastrepo="${repository[0]}"
             lastseen="${image}"
             printf "Pulling $image\n";
             docker pull "${image}"
          done
