name: docker-build-push

on:
  push:
    branches: [ master ]

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            tag: ['latest']
            docker-file: ['Dockerfile']
            module-name: ['antler']

    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alexthiery/modules-${{matrix.module-name}}
          path: ${{matrix.module-name}}
          dockerfile: modules/${{matrix.module-name}}/${{matrix.docker-file}}
          tags:  ${{matrix.tag}}